#application: app-xkcd-cn
#version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /pics
  static_dir: pics

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest
